Repository geoadmin/mf-chsdi3, pull requests merged in 2019-04, with the labels that each got.

#3109 ltrea up unfaelle
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/astra_unfaelle.mako
Labels: data

#3141 OEREB get egrid from service
  chsdi/templates/htmlpopup/oerebkataster.mako
Labels: review

#3127 Add model and mako for ch.swisstopo.swisssurface3d.metadata
  chsdi/models/vector/stopo.py
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_rm.png
  chsdi/templates/htmlpopup/swisssurface3d.mako
Labels: data

#3143 New layer ch.bfe.kehrichtverbrennungsanlagen
  chsdi/models/vector/uvek.py
  chsdi/static/images/legends/ch.bfe.kehrichtverbrennungsanlagen_de.png
  chsdi/static/images/legends/ch.bfe.kehrichtverbrennungsanlagen_en.png
  chsdi/static/images/legends/ch.bfe.kehrichtverbrennungsanlagen_fr.png
  chsdi/static/images/legends/ch.bfe.kehrichtverbrennungsanlagen_it.png
  chsdi/static/images/legends/ch.bfe.kehrichtverbrennungsanlagen_rm.png
  chsdi/templates/htmlpopup/kehrichtverbrennungsanlagen.mako
Labels: data

#3142 ch.swisstopo.vec25-gewaessernetz_referenz
  chsdi/locale/en/LC_MESSAGES/chsdi.po
  chsdi/models/vector/stopo.py
  chsdi/static/images/legends/ch.swisstopo.vec25-gewaessernetz_referenz_de.png
  chsdi/static/images/legends/ch.swisstopo.vec25-gewaessernetz_referenz_en.png
  chsdi/static/images/legends/ch.swisstopo.vec25-gewaessernetz_referenz_fr.png
  chsdi/static/images/legends/ch.swisstopo.vec25-gewaessernetz_referenz_it.png
  chsdi/static/images/legends/ch.swisstopo.vec25-gewaessernetz_referenz_rm.png
  chsdi/templates/htmlpopup/gewaessernetzref.mako
Labels: data

#3166 Update jquery (security)
  package.json
Labels: 1st prio
