Repository geoadmin/mf-chsdi3, pull requests merged in 2019-10, with the labels that each got.

#3268 Geojson for search service
  chsdi/static/doc/source/services/sdiservices.rst
  chsdi/views/search.py
  tests/integration/__init__.py
  tests/integration/test_search.py
Labels: review

#3272 Escaping incoming params (in mako template) before passing them to JS
  chsdi/templates/historicalmaps/zeitreihen_map.mako
  chsdi/templates/luftbilder/lubis_map.mako
Labels: 1st prio

#3278 Multilingual attributes energieberatungsstellen
  chsdi/models/vector/uvek.py
Labels: WIP

#3266 Translation service
  apache/wsgi.conf.in
  chsdi/__init__.py
  chsdi/models/bod.py
  chsdi/views/translations.py
  tests/integration/test_translation.py
Labels: 2nd prio

#3277 releasenotes 2019-10-23
  chsdi/locale/de/LC_MESSAGES/chsdi.po
  chsdi/locale/en/LC_MESSAGES/chsdi.po
  chsdi/locale/fi/LC_MESSAGES/chsdi.po
  chsdi/locale/fr/LC_MESSAGES/chsdi.po
  chsdi/locale/it/LC_MESSAGES/chsdi.po
  chsdi/static/doc/source/releasenotes/index.rst
  chsdi/static/doc/source/services/sdiservices.rst
Labels: WIP
