Repository geoadmin/mf-chsdi3, pull requests merged in 2022-10, with the labels that each got.

#4036 BGDIDIC-2472: Update legends
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_de.png
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_en.png
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_fr.png
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_it.png
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_rm.png
Labels: feature

#4027 BGDIINF_SB-2486: Improving docker image size
  .dockerignore
  .env.ci
  .env.default
  90-chsdi3.conf
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  apache/25-mf-chsdi3.conf.in
  apache/application.wsgi.in
  apache/default.conf.in
  apache/ports.conf.in
  apache/wsgi-py3.conf.in
  buildspec-py3.yml
  chsdi/__init__.py
  chsdi/config/base.ini.in
  chsdi/config/dev.ini.in
  chsdi/config/prod.ini.in
  docker-entrypoint.sh
  setup.cfg
Labels: feature

#4028 BGDIINF_SB-2498: Update to py 3.9 and all packages
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  apache/wsgi-py3.conf.in
  buildspec-py3.yml
  chsdi/lib/helpers.py
  chsdi/models/types.py
  chsdi/static/doc/source/api/integrate_cms.rst
  chsdi/views/catalog.py
  docker-entrypoint.sh
  scripts/rssFeedGen.py
  setup.py
  tests/functional/test_helpers.py
  tests/integration/test_catalog.py
Labels: feature

#4035 Docker image improvements and clean PRs merge into master
  .dockerignore
  .env.ci
  .env.default
  .gitignore
  90-chsdi3.conf
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  README.md
  apache/25-mf-chsdi3.conf.in
  apache/application.wsgi.in
  apache/default.conf.in
  apache/ports.conf.in
  apache/wsgi-py3.conf.in
  buildspec-py3.yml
  chsdi/__init__.py
  chsdi/config/base.ini.in
  chsdi/config/dev.ini.in
  chsdi/config/prod.ini.in
  chsdi/lib/helpers.py
  chsdi/models/types.py
  chsdi/response_callbacks.py
  chsdi/static/doc/source/api/integrate_cms.rst
  chsdi/static/robots_dev.txt
  chsdi/subscribers.py
  chsdi/templates/historicalmaps/viewer.mako
  chsdi/templates/htmlpopup/base.mako
  chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako
  chsdi/templates/htmlpopup/kernkraftwerke.mako
  chsdi/templates/htmlpopup/kgs.mako
  chsdi/templates/htmlpopup/klaeranlagen.mako
  chsdi/templates/htmlpopup/statistikwasserkraftanlagen.mako
  chsdi/templates/htmlpopup/windatlas50.mako
  chsdi/templates/luftbilder/viewer.mako
  chsdi/views/catalog.py
  docker-entrypoint.sh
  scripts/rssFeedGen.py
  setup.cfg
  setup.py
  tests/functional/test_helpers.py
  tests/integration/test_catalog.py
Labels: new-release

#4034 BGDIINF_SB-2496: cleanup - remove all python2 relicts and the module six
  Makefile
  Pipfile
  Pipfile.lock
  chsdi/lib/helpers.py
  chsdi/lib/parser.py
  chsdi/lib/validation/features.py
  chsdi/lib/validation/find.py
  chsdi/lib/validation/identify.py
  chsdi/models/__init__.py
  chsdi/models/vector/__init__.py
  chsdi/renderers.py
  chsdi/subscribers.py
  chsdi/templates/htmlpopup/lubis_schraegaufnahmen.mako
  chsdi/templates/htmlpopup/lubis_terra.mako
  chsdi/templates/htmlpopup/zeitreihen.mako
  chsdi/templates/luftbilder/viewer.mako
  chsdi/views/color.py
  chsdi/views/features.py
  chsdi/views/layers.py
  scripts/rssFeedGen.py
  tests/e2e/test_layers.py
  tests/e2e/test_links.py
  tests/functional/test_helpers.py
  tests/integration/test_doc.py
Labels: feature

#4037 BGDIINF_SB-2534: Updated docu about HTTP allowed method
  chsdi/static/doc/source/index.rst
  chsdi/static/doc/source/services/sdiservices.rst
Labels: feature

#4042 BGDIINF_SB-2631: Added support for JSON logs
  .dockerignore
  .env.ci
  .env.default
  .gitignore
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  apache/25-mf-chsdi3.conf.in
  apache/application.wsgi.in
  apache/default.conf.in
  chsdi/__init__.py
  chsdi/config/base.ini.in
  chsdi/config/dev.ini.in
  chsdi/config/logging-cfg-local.yml
  chsdi/config/prod.ini.in
  chsdi/lib/helpers.py
  chsdi/logging_setup.py
  chsdi/logging_tweens.py
  chsdi/subscribers.py
  docker-entrypoint.sh
Labels: feature

#4044 Fixing CI manual build and versioning
  buildspec-py3.yml
  tests/integration/__init__.py
Labels: bug

#4047 BGDIDIC-993: adding the attribute releasekey to the tooltips of the p…
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/gridstand.mako
Labels: feature

#4048 Removing forgotten paranthesis
  chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako
Labels: bug

#4050 av - setting the parantheis the right place
  chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako
Labels: bug

#4052 Do not log access log to other_vhosts_access.log
  .env.default
  Dockerfile
  apache/25-mf-chsdi3.conf.in
Labels: bug

#4046 releasenotes for deploy 20221026
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature

#4053 New Release 2022-10-26-rc1
  .env.default
  Dockerfile
  apache/25-mf-chsdi3.conf.in
  chsdi/models/vector/stopo.py
  chsdi/static/doc/source/releasenotes/index.rst
  chsdi/templates/htmlpopup/gridstand.mako
Labels: new-release

#4057 Fixing logging for Kibana
  chsdi/logging_tweens.py
  chsdi/subscribers.py
Labels: bug

#4058 Fixed app_version being set to 0000-00-00-rc0- on new release
  buildspec-py3.yml
Labels: bug
