Repository geoadmin/mf-chsdi3, pull requests merged in 2022-04, with the labels that each got.

#3846 Remove field BGDIDIC-342
  chsdi/models/vector/uvek.py
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_de.png
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_en.png
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_fr.png
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_it.png
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_rm.png
  chsdi/templates/htmlpopup/fernwaerme_angebot.mako
Labels: feature

#3847 BGDIDIC-1393: lubis bilder st gallen
  chsdi/templates/htmlpopup/lubis.mako
Labels: data-integration

#3848 BGDIINF_SB-2284: Removed qrcode that has been migrated into a micro service
  chsdi/__init__.py
  chsdi/templates/index.mako
  chsdi/views/qrcode_generator.py
  requirements-py3.txt
  requirements.txt
  tests/integration/test_qrcode.py
Labels: feature

#3851 BGDIINF_SB-2283: Removed service feedback
  chsdi/__init__.py
  chsdi/views/feedback.py
Labels: feature

#3853 Be less restrictive in search integration tests
  tests/integration/test_search.py
Labels: bug

#3850 BGDIINF_SB-2282: Removed kml service and gstyles services
  Makefile
  README.md
  apache/wsgi-py3.conf.in
  apache/wsgi.conf.in
  buildspec-py3.yml
  buildspec.yml
  chsdi/__init__.py
  chsdi/lib/decorators/__init__.py
  chsdi/lib/files_handler.py
  chsdi/lib/helpers.py
  chsdi/templates/adminkml.mako
  chsdi/views/admin.py
  chsdi/views/checker.py
  chsdi/views/files.py
  chsdi/views/glstyles.py
  dev.env
  int.env
  prod.env
  production.ini.in
  rc_dev
  rc_int
  rc_prod
  scripts/replace-scales.py
  tests/e2e/test_layers.py
  tests/e2e/test_varnish.py
  tests/integration/test_admin.py
  tests/integration/test_file_storage.py
  tests/integration/test_glstyles_storage.py
Labels: feature

#3854 BGDIINF_SB-2333: Removed shortener (aka shortlink)
  Makefile
  README.md
  apache/wsgi-py3.conf.in
  apache/wsgi.conf.in
  buildspec-py3.yml
  buildspec.yml
  chsdi/__init__.py
  chsdi/lib/helpers.py
  chsdi/models/clientdata_dynamodb.py
  chsdi/templates/index.mako
  chsdi/views/shortener.py
  dev.env
  int.env
  prod.env
  production.ini.in
  rc_dev
  rc_int
  rc_prod
  tests/functional/test_helpers.py
  tests/integration/__init__.py
  tests/integration/test_shortener.py
Labels: feature

#3857 BGDIINF_SB-2333: Readded loader.js in apache config
  apache/wsgi-py3.conf.in
  apache/wsgi.conf.in
Labels: feature

#3856 BGDIINF_SB-1332 added FAQ entry about fair use
  chsdi/static/doc/source/api/faq/index.rst
Labels: feature

#3865 Fix field name BGDIDIC-308
  chsdi/models/vector/bafu.py
  chsdi/templates/htmlpopup/auen_ausserhalb_bundinv_alpin.mako
Labels: feature
