Repository geoadmin/mf-chsdi3, pull requests merged in 2022-09, with the labels that each got.

#4008 BGDIINF_SB-2567: Removed the WMTS/WMS layer tests
  tests/e2e/__init__.py
  tests/e2e/test_wms.py
  tests/e2e/test_wmtsgettile.py
Labels: feature

#4009 BGDIDIC-278 strassenverkehrszaehlung-uebergeordnet
  chsdi/templates/htmlpopup/verkehrszaehlung_uebergeordnet.mako
Labels: data-integration

#4012 BGDIDIC-2442: added legends to waldgrenze
  chsdi/static/images/legends/ch.bafu.wald-obere_waldgrenze_de.png
  chsdi/static/images/legends/ch.bafu.wald-obere_waldgrenze_en.png
  chsdi/static/images/legends/ch.bafu.wald-obere_waldgrenze_fr.png
  chsdi/static/images/legends/ch.bafu.wald-obere_waldgrenze_it.png
  chsdi/static/images/legends/ch.bafu.wald-obere_waldgrenze_rm.png
Labels: feature

#4013 With this fix the make legends can call localhost as well:
  Makefile
  scripts/downloadlegends.sh
Labels: bug

#4010 releasenotes for deploy 2022-09-07
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature

#4019 Removed useless service-alti apache config
  apache/wsgi-py3.conf.in
  buildspec-py3.yml
Labels: feature

#4020 BGDIINF_SB-2569: Makefile.ireland and README_IRELAND.md are obsolete and can be deleted
  Makefile.ireland
  README_IRELAND.md
Labels: feature

#4021 Feat bgdidic 2474 bfe elektrische anlagen ueber 36
  chsdi/models/vector/uvek.py
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_de.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_en.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_fr.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_it.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_rm.png
  chsdi/templates/htmlpopup/bfe_elektrische_anlagen_ueber_36_line.mako
  chsdi/templates/htmlpopup/bfe_elektrische_anlagen_ueber_36_point.mako
  chsdi/templates/htmlpopup/bfe_elektrische_anlagen_ueber_36_poly.mako
Labels: feature

#4011 BGDIINF_SB-2506: using pipenv to build the project
  .dockerignore
  .env.ci
  Dockerfile
  Makefile
  Pipfile
  Pipfile.lock
  requirements-py3.txt
  setup.py
Labels: feature

#4023 BGDIINF_SB-2486: Removed deprecated iipimage - #1
  Makefile
  apache/wsgi-py3.conf.in
Labels: feature

#4024 BGDIINF_SB-2486: Removed static assets url rewrite from apache - #2
  .dockerignore
  .env.ci
  .gitignore
  Makefile
  Pipfile
  Pipfile.lock
  apache/wsgi-py3.conf.in
  chsdi/__init__.py
  chsdi/response_callbacks.py
  chsdi/static/robots.txt
  chsdi/static/robots_dev.txt
  chsdi/subscribers.py
  docker-entrypoint.sh
  pyramid-config/base.ini.in
Labels: feature

#4029 Using an environment variable for the data.geo.admin.ch protocol
  .env.ci
  .env.default
  Makefile
  chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako
  chsdi/templates/htmlpopup/fliessgewaesser_typ.mako
  chsdi/templates/htmlpopup/gebaeuderegister.mako
  chsdi/templates/htmlpopup/geotechnik_gk200.mako
  chsdi/templates/htmlpopup/geotechnik_mineralische_rohstoffe200.mako
  chsdi/templates/htmlpopup/geotope.mako
  chsdi/templates/htmlpopup/geschiebemessnetz.mako
  chsdi/templates/htmlpopup/gewaesserschutz_badewasserqualitaet.mako
  chsdi/templates/htmlpopup/hydrogeologische-karte_100.mako
  chsdi/templates/htmlpopup/ivs_nat.mako
  chsdi/templates/htmlpopup/karst-einzugsgebiete.mako
  chsdi/templates/htmlpopup/kgs.mako
  chsdi/templates/htmlpopup/lubis_terra.mako
Labels: bug

#4030 BGDIINF_SB-1918: Define in doc, that not always sr=4326 is possible
  chsdi/static/doc/source/services/sdiservices.rst
Labels: bug
