Repository geoadmin/mf-chsdi3, pull requests merged in 2022-11, with the labels that each got.

#4059 Use Pipfile.lock on the CI
  Makefile
  buildspec-py3.yml
Labels: bug

#4062 Feat bgdidic 2494 gewaesser uferbestockung
  chsdi/models/vector/bafu.py
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_de.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_en.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_fr.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_it.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_rm.png
  chsdi/templates/htmlpopup/bafu_gewaesser_uferbestockung.mako
Labels: feature

#4063 BGDIDIC-2523: new lfh layers
  chsdi/models/vector/uvek.py
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-klein_de.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-klein_en.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-klein_fr.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-klein_it.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-klein_rm.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_de.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_en.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_fr.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_it.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_rm.png
Labels: data-integration

#4061 Feat bgdidic 2472 drohnen
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/einschraenkungen_drohnen.mako
  chsdi/templates/htmlpopup/gebietsbeschraenkungen_drohnen.mako
Labels: feature

#4066 BGDIDIC-2472: update legends
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_de.png
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_en.png
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_fr.png
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_it.png
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_rm.png
Labels: feature

#4060 BGDIINF_SB-2580: Removing e2e tests moved towards infra-e2e-tests
  chsdi/static/images/legends/ch.bfe.erneuerbarheizen_de.png
  chsdi/static/images/legends/ch.bfe.erneuerbarheizen_en.png
  chsdi/static/images/legends/ch.bfe.erneuerbarheizen_fr.png
  chsdi/static/images/legends/ch.bfe.erneuerbarheizen_it.png
  chsdi/static/images/legends/ch.bfe.erneuerbarheizen_rm.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_de.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_en.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_fr.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_it.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_rm.png
  chsdi/static/images/legends/ch.swisstopo.geologie-tiefengeothermie_projekte_de.png
  chsdi/static/images/legends/ch.swisstopo.geologie-tiefengeothermie_projekte_en.png
  chsdi/static/images/legends/ch.swisstopo.geologie-tiefengeothermie_projekte_fr.png
  chsdi/static/images/legends/ch.swisstopo.geologie-tiefengeothermie_projekte_it.png
  chsdi/static/images/legends/ch.swisstopo.geologie-tiefengeothermie_projekte_rm.png
  tests/e2e/test_layers.py
Labels: feature

#4068 Feat bgdidic 2532 halteplaetze
  chsdi/models/vector/bak.py
  chsdi/static/images/legends/ch.bak.halteplaetze-jenische_sinti_roma_de.png
  chsdi/static/images/legends/ch.bak.halteplaetze-jenische_sinti_roma_en.png
  chsdi/static/images/legends/ch.bak.halteplaetze-jenische_sinti_roma_fr.png
  chsdi/static/images/legends/ch.bak.halteplaetze-jenische_sinti_roma_it.png
  chsdi/static/images/legends/ch.bak.halteplaetze-jenische_sinti_roma_rm.png
  chsdi/templates/htmlpopup/halteplaetze_jenische_sinti_roma.mako
Labels: feature

#4067 BGDIDIC-2472: add field translations
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/einschraenkungen_drohnen.mako
Labels: feature

#4069 BGDIDIC-1049: adapt url format
  chsdi/templates/htmlpopup/einschraenkungen_drohnen.mako
Labels: feature

#4072 BGDIDIC-1049: fix tr
  chsdi/templates/htmlpopup/einschraenkungen_drohnen.mako
Labels: feature

#4070 BGDIINF_SB-2653: expose pool and transaction settings to the
  .env.ci
  chsdi/config/base.ini.in
  chsdi/models/__init__.py
  chsdi/views/features.py
  tests/integration/test_features_service.py
Labels: feature

#4065 BGDIDIC-2494: add legends
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_vegetation_de.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_vegetation_en.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_vegetation_fr.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_vegetation_it.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_vegetation_rm.png
Labels: feature

#4074 BGDIDIC-935: add new attribute gkat to basic tooltip
  chsdi/templates/htmlpopup/gebaeuderegister.mako
Labels: feature

#4073 Describing the option SCALE to the cmd make legends
  Makefile
Labels: feature

#4077 Feat bgdidic 342 fernwaerme angebot
  chsdi/models/vector/uvek.py
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_de.png
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_en.png
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_fr.png
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_it.png
  chsdi/static/images/legends/ch.bfe.fernwaerme-angebot_rm.png
  chsdi/templates/htmlpopup/fernwaerme_angebot.mako
Labels: feature

#4078 BGDIDIC-2494: update legends
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_de.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_en.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_fr.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_it.png
  chsdi/static/images/legends/ch.bafu.gewaesser-uferbestockung_rm.png
Labels: feature

#4079 BGDIDIC-2472: update legends
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_de.png
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_en.png
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_fr.png
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_it.png
  chsdi/static/images/legends/ch.bazl.einschraenkungen-drohnen_rm.png
Labels: feature

#4080 BGDIDIC-1125: Update legend of richtfunkverbindungen
  chsdi/static/images/legends/ch.bakom.richtfunkverbindungen_de.png
  chsdi/static/images/legends/ch.bakom.richtfunkverbindungen_en.png
  chsdi/static/images/legends/ch.bakom.richtfunkverbindungen_fr.png
  chsdi/static/images/legends/ch.bakom.richtfunkverbindungen_it.png
  chsdi/static/images/legends/ch.bakom.richtfunkverbindungen_rm.png
Labels: feature

#4081 BGDIDIC-2537: adapt geocat links
  chsdi/templates/legend.mako
Labels: feature
