Repository geoadmin/mf-chsdi3, pull requests merged in 2022-08, with the labels that each got.

#3978 BGDIINF_SB-2488 bugfix : sdi services crashes on queries with specific SRID
  chsdi/models/bod.py
Labels: bug

#3979 BGDIINF_SB-2517: Set default cache-control header within pyramid application
  .env.ci
  Makefile
  Makefile.frankfurt
  apache/wsgi-py3.conf.in
  base.ini.in
  chsdi/response_callbacks.py
  chsdi/subscribers.py
  production.ini.in
  setup.cfg
  tests/integration/__init__.py
  tests/integration/test_checker.py
Labels: feature

#3849 BGDIINF_SB-2326: Changed loader.js endpoint to use sys-api3 instead of sys-public
  .env.ci
  .env.default
  Makefile
  base.ini.in
  buildspec.yml
  chsdi/views/loader.py
  production.ini.in
  rc_dev
  rc_int
  rc_prod
Labels: feature, TO-BE-MERGE-AFTER-MIGRATION

#3985 all notruf models pointing to bakom.notruf table
  chsdi/models/vector/uvek.py
Labels: bug

#3986 BGDIINF_SB-2454: Make frankfurt the default Makefile
  Makefile
  Makefile.frankfurt
  Makefile.ireland
  PYTHON3.md
  README.md
  buildspec-py3.yml
  buildspec.yml
  deploy/hooks/post-restore-code
  scripts/delete_branch.sh
  scripts/deploybranch.sh
  scripts/deploydev.sh
  scripts/nose_run.sh
Labels: feature

#3987 BGDIINF_SB-2516: Moved CORS headers settings from apache into pyramid app
  apache/wsgi-py3.conf.in
  chsdi/response_callbacks.py
  chsdi/subscribers.py
Labels: feature

#3990 BGDIINF_SB-2540: data.geo.admin.ch makes a redirect on https calls
  chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako
Labels: bug

#3991 BGDIINF_SB-2353 Fixed CI manual build on branch master
  buildspec-py3.yml
Labels: bug

#3992 BGDIINF_SB-2540: OpenData av hopping that this fix will work in a https setup
  chsdi/templates/htmlpopup/cadastralwebmap_opendata.mako
Labels: bug

#3995 BGDIINF_SB-2454: drop Ireland support, only go for Frankfurt
  .dockerignore
  .gitignore
  Makefile
  PYTHON3.md
  README.md
  README_IRELAND.md
  buildspec.yml
  deploy/conf/00-branch.conf.in
  deploy/deploy-branch.cfg.in
  deploy/deploy.cfg
  deploy/hooks/post-restore
  deploy/hooks/post-restore-code
  deploy/hooks/pre-restore
  rc_branch.mako
  rc_ci
  rc_dev
  rc_int
  rc_prod
  rc_user
  scripts/check_python3_compatibility.sh
  scripts/delete_branch.sh
  scripts/deploybranch.sh
  scripts/deploydev.sh
  scripts/deploysnapshot.sh
  scripts/nose_run.sh
  scripts/test_sphinxserver.py
  scripts/translation2po.py
Labels: feature

#3999 BGDIINF_SB-2454: Removed python 2.7 and Ireland specific files
  apache/application.wsgi.mako
  apache/wsgi.conf.in
  development.ini.in
  production.ini.in
  requirements.txt
Labels: feature

#3997 BGDIINF_SB-2542: remove SearchServer related parts of code as they are obsoleted by the migration to Frankfurt
  .env.ci
  .env.default
  Makefile
  base.ini.in
  chsdi/__init__.py
  chsdi/lib/helpers.py
  chsdi/lib/mortonspacekey.py
  chsdi/lib/sphinxapi/__init__.py
  chsdi/lib/sphinxapi/sphinxapi.py
  chsdi/lib/validation/search.py
  chsdi/templates/luftbilder/viewer.mako
  chsdi/views/search.py
  tests/functional/test_mortonspacekey.py
  tests/integration/test_search.py
  tests/integration/test_sphinxapi.py
Labels: feature

#3998 BGDIINF_SB-1825: Removed WMTS GetCap DB model
  chsdi/models/bod.py
Labels: feature

#4000 Improved pyramid config folder structure
  Dockerfile
  Makefile
  docker-entrypoint.sh
  pyramid-config/base.ini.in
  pyramid-config/dev.ini.in
  pyramid-config/prod.ini.in
Labels: feature

#4001 SB_BGDIINF_SB-2488 bugfix ; solving crashes on sdi services queries with SR 4326 and 3857
  chsdi/models/bod.py
Labels: bug

#4003 Fix for dataintegration:
  chsdi/lib/helpers.py
Labels: bug, new-release

#3980 BGDIDIC-2472: Add ch.bazl.gebietsbeschraenkungen-drohnen
  chsdi/models/vector/uvek.py
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_de.png
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_en.png
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_fr.png
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_it.png
  chsdi/static/images/legends/ch.bazl.gebietsbeschraenkungen-drohnen_rm.png
  chsdi/templates/htmlpopup/gebietsbeschraenkungen_drohnen.mako
Labels: feature

#4004 Fixed mako with versionned urls
  Dockerfile
  Makefile
  buildspec-py3.yml
  chsdi/static/info.json.in
Labels: bug

#4002 BGDIINF_SB-2554: using host header and protocol in url construction in loader.js
  .env.ci
  .env.default
  chsdi/__init__.py
  chsdi/subscribers.py
  chsdi/views/loader.py
  pyramid-config/base.ini.in
Labels: feature

#3976 BGDIDIC-79: Update attributes sperrungen_umleitungen
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/sperrungen_umleitungen.mako
Labels: feature
