Repository geoadmin/mf-chsdi3, pull requests merged in 2022-03, with the labels that each got.

#3811 New dynamodb parameter
  chsdi/views/shortener.py
Labels: feature

#3814 Fixed CI issus due to pg sandbox and integration tests
  buildspec-py3.yml
  int.env
  tests/integration/test_features_service.py
Labels: bug

#3803 Fix the link pointing on terms of use
  chsdi/static/doc/source/index.rst
Labels: bug

#3813 BGDIINF_SB-2258: Improved CI performance of ~2x and some CI clean up
  .gitignore
  Dockerfile
  Makefile
  buildspec-py3.yml
  buildspec.yml
  setup.cfg
Labels: feature

#3815 Exclude geojson layer from tooltips layer (docu only)
  chsdi/static/doc/source/api/faq/index.rst
  chsdi/views/layers.py
Labels: bug

#3804 BGDIDIC-2287: Update legend png
  chsdi/static/images/legends/ch.bazl.projektierungszonen-flughafenanlagen_de.png
  chsdi/static/images/legends/ch.bazl.projektierungszonen-flughafenanlagen_en.png
  chsdi/static/images/legends/ch.bazl.projektierungszonen-flughafenanlagen_fr.png
  chsdi/static/images/legends/ch.bazl.projektierungszonen-flughafenanlagen_it.png
  chsdi/static/images/legends/ch.bazl.projektierungszonen-flughafenanlagen_rm.png
Labels: data-integration

#3816 Introduce geoprtal url
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/cadastralwebmap.include.mako
Labels: feature

#3825 Feat bgdidic 698 diemo oicp adaption chsdi
  chsdi/models/vector/diemo.py
Labels: feature

#3795 BGDIDIC-295 & BGDIDIC-1992: Adapt tool-tip
  chsdi/templates/htmlpopup/erneuerbarheizen.mako
  chsdi/templates/htmlpopup/erneuerbarheizen_mfh.mako
Labels: data-integration

#3826 Update legends BGDIDIC-1755
  chsdi/static/images/legends/ch.bazl.sicherheitszonenplan_fr.png
  chsdi/static/images/legends/ch.bazl.sicherheitszonenplan_it.png
Labels: feature

#3828 Update legends BGDIDIC-965
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_de.png
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_de_big.pdf
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_en.png
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_en_big.pdf
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_fr.png
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_fr_big.pdf
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_it.png
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_it_big.pdf
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_rm.png
  chsdi/static/images/legends/ch.bazl.luftfahrtkarten-icao_rm_big.pdf
Labels: feature

#3829 Update legends BGDIDIC-671
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_de.png
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_de_big.pdf
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_en.png
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_en_big.pdf
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_fr.png
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_fr_big.pdf
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_it.png
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_it_big.pdf
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_rm.png
  chsdi/static/images/legends/ch.vbs.sperr-gefahrenzonenkarte_rm_big.pdf
Labels: feature

#3830 Update legends BGDIDIC-1025
  chsdi/static/images/legends/ch.vbs.milairspacechart_de.png
  chsdi/static/images/legends/ch.vbs.milairspacechart_de_big.pdf
  chsdi/static/images/legends/ch.vbs.milairspacechart_en.png
  chsdi/static/images/legends/ch.vbs.milairspacechart_en_big.pdf
  chsdi/static/images/legends/ch.vbs.milairspacechart_fr.png
  chsdi/static/images/legends/ch.vbs.milairspacechart_fr_big.pdf
  chsdi/static/images/legends/ch.vbs.milairspacechart_it.png
  chsdi/static/images/legends/ch.vbs.milairspacechart_it_big.pdf
  chsdi/static/images/legends/ch.vbs.milairspacechart_rm.png
  chsdi/static/images/legends/ch.vbs.milairspacechart_rm_big.pdf
Labels: feature

#3827 Update legends BGDIDIC-1167
  chsdi/static/images/legends/ch.bazl.segelflugkarte_de.png
  chsdi/static/images/legends/ch.bazl.segelflugkarte_de_big.pdf
  chsdi/static/images/legends/ch.bazl.segelflugkarte_en.png
  chsdi/static/images/legends/ch.bazl.segelflugkarte_en_big.pdf
  chsdi/static/images/legends/ch.bazl.segelflugkarte_fr.png
  chsdi/static/images/legends/ch.bazl.segelflugkarte_fr_big.pdf
  chsdi/static/images/legends/ch.bazl.segelflugkarte_it.png
  chsdi/static/images/legends/ch.bazl.segelflugkarte_it_big.pdf
  chsdi/static/images/legends/ch.bazl.segelflugkarte_rm.png
  chsdi/static/images/legends/ch.bazl.segelflugkarte_rm_big.pdf
Labels: feature

#3818 BGDIDIC-154: Rename attributes ch.swisstopo.amtliches-gebaeudeadressverzeichnis
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/addressverzeichnis.mako
Labels: feature

#3831 Delete fields BGDIDIC-1542
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/minergiegebaeude.mako
Labels: feature

#3821 Add lang fields BGDIDIC-935
  chsdi/models/vector/edi.py
  chsdi/templates/htmlpopup/gebaeuderegister.mako
Labels: feature

#3832 Remove legend link BGDIDIC-113
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_de.png
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_de_big.pdf
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_en.png
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_en_big.pdf
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_fr_big.pdf
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_it.png
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_it_big.pdf
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisstlm3d-gewaessernetz_rm_big.pdf
  chsdi/templates/legend.mako
Labels: feature

#3842 Fix turbine number BGDIDIC-1700
  tests/integration/test_features_service.py
Labels: bug

#3843 fix windenergie tests
  tests/integration/test_features_service.py
Labels: skip-release-note

#3838 Fix null case BGDIDIC-1061
  chsdi/templates/htmlpopup/flugplaetze_heliports.mako
Labels: feature

#3841 Add lang urls BGDIDIC-1897
  chsdi/models/vector/vbs.py
  chsdi/templates/htmlpopup/kataster_belasteter_standorte_militaer.mako
Labels: feature

#3839 Add lang urls BGDIDIC-1344
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/kataster_belasteter_standorte_zivflpl.mako
Labels: feature

#3840 Add lang urls BGDIDIC-1375
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/kataster_belasteter_standorte_oev.mako
Labels: feature
