Repository geoadmin/mf-chsdi3, pull requests merged in 2022-05, with the labels that each got.

#3855 Deshopify ch.swisstopo.geologie-geocover
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/geocover_aux.mako
  chsdi/templates/htmlpopup/geocover_point_drill.mako
  chsdi/templates/htmlpopup/geocover_point_hydro.mako
  chsdi/templates/htmlpopup/geocover_point_info.mako
  chsdi/templates/htmlpopup/geocover_point_struct.mako
  chsdi/templates/htmlpopup/geocover_polygon.mako
Labels: data-integration

#3860 Deshopify ch.swisstopo.geologie-geologischer_atlas
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/ga25_line_aux.mako
  chsdi/templates/htmlpopup/ga25_point_drill.mako
  chsdi/templates/htmlpopup/ga25_point_hydro.mako
  chsdi/templates/htmlpopup/ga25_point_info.mako
  chsdi/templates/htmlpopup/ga25_point_struct.mako
  chsdi/templates/htmlpopup/ga25_polygon.mako
Labels: data-integration

#3861 Deshopify ch.swisstopo.geologie-geocover.metadata
  chsdi/models/vector/stopo.py
  chsdi/static/images/legends/ch.swisstopo.geologie-geocover.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.geologie-geocover.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.geologie-geocover.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.geologie-geocover.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.geologie-geocover.metadata_rm.png
  chsdi/templates/htmlpopup/geocover_metadata.mako
Labels: data-integration

#3862 Deshopify ch.swisstopo.geologie-geologischer_atlas[*].metadata
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/geologischer_atlas_meta.mako
Labels: data-integration

#3863 Deshopify ch.swisstopo.geologie-generalkarte-ggk200.metadata
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/generalkarte_ggk200.metadata.mako
Labels: data-integration

#3864 Deshopify ch.swisstopo.geologie-spezialkarten_schweiz[*].metadata
  chsdi/models/vector/stopo.py
  chsdi/static/images/legends/ch.swisstopo.geologie-spezialkarten_schweiz.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.geologie-spezialkarten_schweiz.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.geologie-spezialkarten_schweiz.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.geologie-spezialkarten_schweiz.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.geologie-spezialkarten_schweiz.metadata_rm.png
  chsdi/templates/htmlpopup/spezialkarten_meta.mako
Labels: data-integration

#3845 BGDIDIC-983: new metageometries for pk25/50/100, remove shop attributes from several swisstopo layer
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/dufour_meta.mako
  chsdi/templates/htmlpopup/gridstand.mako
  tests/integration/test_features_service.py
Labels: data-integration

#3859 Update legends ch.are.wohnungsinventar-zweitwohnungsanteil
  chsdi/static/images/legends/ch.are.wohnungsinventar-zweitwohnungsanteil_de.png
  chsdi/static/images/legends/ch.are.wohnungsinventar-zweitwohnungsanteil_en.png
  chsdi/static/images/legends/ch.are.wohnungsinventar-zweitwohnungsanteil_fr.png
  chsdi/static/images/legends/ch.are.wohnungsinventar-zweitwohnungsanteil_it.png
  chsdi/static/images/legends/ch.are.wohnungsinventar-zweitwohnungsanteil_rm.png
Labels: data-integration

#3844 Rework ch.swisstopo.amtliches-strassenverzeichnis
  chsdi/models/vector/stopo.py
  chsdi/static/doc/source/services/sdiservices.rst
  chsdi/templates/htmlpopup/strassenverzeichnis.mako
  tests/integration/test_features_service.py
  tests/integration/test_identify_service.py
Labels: feature

#3867 Add ch.swisstopo.geologie-geologischer_atlas_profile
  chsdi/models/vector/stopo.py
  chsdi/static/images/legends/ch.swisstopo.geologie-geologischer_atlas_profile_de.png
  chsdi/static/images/legends/ch.swisstopo.geologie-geologischer_atlas_profile_en.png
  chsdi/static/images/legends/ch.swisstopo.geologie-geologischer_atlas_profile_fr.png
  chsdi/static/images/legends/ch.swisstopo.geologie-geologischer_atlas_profile_it.png
  chsdi/static/images/legends/ch.swisstopo.geologie-geologischer_atlas_profile_rm.png
  chsdi/templates/htmlpopup/geologischer_atlas_profil.mako
Labels: data-integration

#3869 Feat bgdidic 1457 obstacles
  chsdi/models/vector/uvek.py
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderung_de.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderung_en.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderung_fr.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderung_it.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderung_rm.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderungen_de.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderungen_en.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderungen_fr.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderungen_it.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis-aenderungen_rm.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_de.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_en.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_fr.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_it.png
  chsdi/static/images/legends/ch.bazl.luftfahrthindernis_rm.png
  chsdi/templates/htmlpopup/luftfahrthindernisse.mako
  tests/integration/test_features_service.py
  tests/integration/test_identify_service.py
Labels: feature

#3875 Fix identify tests
  tests/integration/test_identify_service.py
Labels: bug

#3882 BGDIINF_SB-2328, BGDIINF_SB-2347: Removed alti e2e tests
  .gitattributes
  Makefile
  buildspec-py3.yml
  buildspec.yml
  dev.env
  int.env
  prod.env
  production.ini.in
  rc_ci
  rc_dev
  rc_int
  rc_prod
  tests/e2e/test_varnish.py
Labels: feature

#3883 BGDIINF_SB-2328: Removed useless CMS environment variable
  Makefile
  buildspec-py3.yml
  buildspec.yml
  dev.env
  int.env
  prod.env
  production.ini.in
  rc_dev
  rc_int
  rc_prod
Labels: feature

#3887 BGDIINF_SB-2328: copied the dockerrun Makefile target from the branch migrate-and-dockerize to here
  Makefile
Labels: feature

#3885 feature_BGDIINF_SB-2328: sorted and cleaned up dev.env entries
  dev.env
Labels: feature

#3889 BGDIINF_SB-2328: Put all logs to stdout
  25-mf-chsdi3.conf.in
  apache/default.conf.in
  development.ini.in
  production.ini.in
Labels: feature

#3890 BGDIINF_SB-2328: new clean Makefile specific for docker/python3/Frankfurt
  Makefile
  Makefile.frankfurt
Labels: feature

#3893 BGDIINF_SB-2328_ Building and runing a docker image
  .dockerignore
  Dockerfile
  Makefile.frankfurt
  apache/ports.conf.in
  docker-entrypoint.sh
Labels: feature

#3895 BGDIINF_SB-2328 use the new pg replica dns pg-geodata-replica.bgdi.ch in frankfurt
  dev.env
  int.env
  prod.env
Labels: feature

#3900 BGDIINF_SB-2328: introducing a flag INSIDE_DOCKER_IMAGE to Makefile.frankfurt for reducing size of docker image
  .dockerignore
  Dockerfile
  Makefile.frankfurt
Labels: feature, data-integration
