Repository geoadmin/mf-chsdi3, pull requests merged in 2022-02, with the labels that each got.

#3797 fix failing search test
  tests/integration/test_search.py
Labels: bug, skip-release-note

#3798 fix failing search test
  tests/integration/test_search.py
Labels: bug, skip-release-note

#3799 remove model from deprecated layer
  chsdi/models/vector/kogis.py
  chsdi/models/vector/stopo.py
  tests/integration/test_features_service.py
Labels: bug, skip-release-note

#3805 Bug fix make templates
  Makefile
  development.ini.in
Labels: bug

#3806 BGDIINF_SB-2174: fix rest/services/api/MapServer/ch.vbs.schiessanzeigen
  chsdi/models/vector/vbs.py
  chsdi/templates/htmlpopup/schiessanzeigen.mako
Labels: bug

#3793 BGDIDIC-1393: Bugfix tooltips
  chsdi/templates/htmlpopup/lubis.mako
Labels: bug

#3802 BGDIINF_SB-2169: remove cut service
  chsdi/__init__.py
  chsdi/lib/validation/geometryservice.py
  chsdi/models/__init__.py
  chsdi/models/vector/stopo.py
  chsdi/templates/index.mako
  chsdi/views/features.py
  tests/integration/test_features_service.py
Labels: feature

#3792 BGDIDIC-1744: ch.swisstopo-vd.stand-oerebkataster: Paralellbetrieb
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/oerebkataster.mako
Labels: data-integration
