Repository geoadmin/mf-chsdi3, pull requests merged in 2022-06, with the labels that each got.

#3896 BGDIINF_SB-2328: Removing the var DEPLOY_TARGET
  .env.default
  Makefile.frankfurt
  PYTHON3.md
  buildspec-py3.yml
  docker-entrypoint.sh
  int.env
  local.ini.in
  prod.env
Labels: feature

#3902 BGDIINF_SB-2328: fixing the old sqlalchemy warning
  requirements-py3.txt
Labels: feature

#3910 BGDIDIC-1678: Update data uri
  chsdi/templates/htmlpopup/statistikwasserkraftanlagen.mako
Labels: feature

#3909 Fix linkeddatahost urls
  buildspec-py3.yml
  buildspec.yml
  chsdi/static/doc/source/services/sdiservices.rst
  rc_dev
  rc_int
  rc_prod
Labels: bug

#3911 BGDIINF_SB-2328: allowing to use env vars from ENV_FILE in Makefile.frankfurt
  Makefile.frankfurt
Labels: feature

#3915 BGDIINF_SB-2328: added dockerpush target to Makefile.frankfurt
  Makefile.frankfurt
Labels: feature

#3919 BGDIDIC-645: cast dict element to string before applying startswith
  chsdi/templates/htmlpopup/kgs.mako
  chsdi/templates/htmlpopup/lubis.mako
Labels: bug

#3921 BGDIINF_SB-2414: Added secrets.yml for summon
  .gitignore
  scripts/translation2po.py
  secrets.yml
Labels: feature

#3920 BGDIINF_SB-2356: updated API docu
  chsdi/static/doc/source/services/sdiservices.rst
Labels: feature

#3924 BGDIINF_SB-2426: Clean up the docker image
  .dockerignore
  .env.default
  .gitignore
  Dockerfile
  Makefile.frankfurt
  PYTHON3.md
  chsdi/models/__init__.py
  docker-entrypoint.sh
  local.ini.in
  prod.ini.in
  secrets.yml
Labels: feature

#3925 BGDIINF_SB-2445: Python3 support bug fix
  chsdi/templates/htmlpopup/ivs_nat.mako
  chsdi/templates/htmlpopup/kgs.mako
  chsdi/templates/luftbilder/viewer.mako
Labels: bug

#3926 BGDIINF_SB-2446: Fixed local run with Makefile.frankfurt
  .gitignore
  Makefile.frankfurt
  PYTHON3.md
  chsdi/models/__init__.py
  tests/integration/test_stationboard.py
Labels: bug

#3928 BGDIINF_SB-2447: No more auth for info.json
  Makefile.frankfurt
  apache/wsgi-py3.conf.in
  apache/wsgi.conf.in
  chsdi/templates/info.json.mako
  info.json.in
Labels: feature

#3931 BGDIINF_SB-2447: Fix the kgs mako to run with py2 and py3
  Makefile.frankfurt
  chsdi/templates/htmlpopup/kgs.mako
  chsdi/templates/htmlpopup/lubis.mako
  chsdi/templates/htmlpopup/lubis_schraegaufnahmen.mako
  chsdi/templates/htmlpopup/lubis_terra.mako
  chsdi/templates/htmlpopup/statistikwasserkraftanlagen.mako
  chsdi/templates/htmlpopup/zeitreihen.mako
Labels: bug

#3884 BGDIINF_SB-2427: Use frankfurt makefile in buildspec-py3.yml
  .env.ci
  .gitignore
  Makefile.frankfurt
  apache/wsgi-py3.conf.in
  buildspec-py3.yml
  chsdi/subscribers.py
  tests/integration/test_features_service.py
Labels: feature

#3929 BGDIINF_SB-2425: Fixing `make -f Makefile.frankfurt test`
  Makefile.frankfurt
  PYTHON3.md
Labels: bug

#3934 BGDIINF_SB_2418: added short comment in .env.default
  .env.default
Labels: feature

#3933 Improved building target dependencies
  Makefile.frankfurt
  PYTHON3.md
  scripts/downloadlegends.sh
Labels: feature

#3932 BGDIINF_SB-2449: fix nosetests and mako issues (python3/pyhton2)
  chsdi/templates/htmlpopup/aktuelle_erdbeben.mako
  chsdi/templates/htmlpopup/biogeoreg.mako
  chsdi/templates/htmlpopup/kernkraftwerke.mako
  chsdi/templates/htmlpopup/kgs.mako
  chsdi/templates/htmlpopup/lubis.mako
  chsdi/templates/htmlpopup/lubis_schraegaufnahmen.mako
  chsdi/templates/htmlpopup/lubis_terra.mako
  chsdi/templates/htmlpopup/ngamapping.mako
  chsdi/templates/htmlpopup/windenergieanlagen_facility.mako
  chsdi/templates/htmlpopup/zeitreihen.mako
  tests/e2e/test_layers.py
Labels: feature

#3938 BGDIINF_SB-2423: app_version
  .gitignore
  Dockerfile
  Makefile.frankfurt
  base.ini.in
  base_version.ini.in
  buildspec-py3.yml
  dev.ini.in
  prod.ini.in
Labels: feature

#3941 Speed up dockerbuild process
  Dockerfile
Labels: feature

#3940 BGDIINF_SB-2372 Fixing doc
  chsdi/static/doc/source/api/doc.rst
  chsdi/static/doc/source/services/sdiservices.rst
Labels: bug

#3942 BGDIINF_SB-2465: Improved logging and made the application log level configurable
  .env.ci
  .env.default
  25-mf-chsdi3.conf.in
  Dockerfile
  base.ini.in
  base_version.ini.in
  dev.ini.in
  docker-entrypoint.sh
  prod.ini.in
Labels: feature

#3945 Fixed LINKEDDATAHOST for Frankfurt setup after merge from master
  .env.ci
  .env.default
Labels: bug, data-integration

#3950 BGDIINF_SB-2475: VECTOR_BUCKET name is now defined when running test target
  .env.default
  Makefile.frankfurt
Labels: feature

#3946 fix failing e2e tests test_all_ids_mapping
  chsdi/models/vector/stopo.py
  tests/e2e/test_layers.py
  tests/e2e/test_links.py
Labels: bug

#3930 BGDIDIC-1786: add fida/hfp1 model and mako
  chsdi/models/vector/kogis.py
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/fida_hfp1.mako
  chsdi/templates/htmlpopup/fida_lfp1.mako
Labels: feature

#3952 Feature bgdidic 983 update legends
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_rm.png
Labels: feature

#3948 BGDIDIC-2173: Update legends kataster
  chsdi/static/images/legends/ch.bav.kataster-belasteter-standorte-oev_fr.png
  chsdi/static/images/legends/ch.bazl.kataster-belasteter-standorte-zivilflugplaetze_fr.png
  chsdi/static/images/legends/ch.vbs.kataster-belasteter-standorte-militaer_fr.png
Labels: feature

#3954 do not use any locale settings for the integer format
  chsdi/templates/htmlpopup/windenergieanlagen_facility.mako
  chsdi/templates/htmlpopup/windenergieanlagen_turbine.mako
Labels: bug

#3935 BGDIDIC-1265: landesschwerenetz
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/landesschwerenetz.mako
Labels: feature

#3959 BGDIDIC-1265: move datasource from kogis_master to stopo_master
  chsdi/models/vector/kogis.py
  chsdi/models/vector/stopo.py
Labels: feature

#3963 BGDIINF_SB-2481: install apache mod_deflate in docker to enable compression
  25-mf-chsdi3.conf.in
  Dockerfile
Labels: feature

#3951 Removed useless ENV variable and targets in Makefile
  Makefile
  Makefile.frankfurt
Labels: bug
