Repository geoadmin/mf-chsdi3, pull requests merged in 2023-10, with the labels that each got.

#4263 add missing compare links
  chsdi/static/doc/source/releasenotes/index.rst
Labels: bug

#4276 BGDIDIC-1706: adding new style 4 ch.bafu.hydroweb-wankarte_national
  chsdi/static/vectorStyles/ch.bafu.hydroweb-warnkarte_national.json
Labels: feature

#4278 BGDIDIC-1706: vectorStyle - change of colour on ch.bafu.hydroweb-warn…
  chsdi/static/vectorStyles/ch.bafu.hydroweb-warnkarte_national.json
Labels: data-integration

#4277 BGDIDIC-1296 update legend png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_de.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_en.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_fr.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_it.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_rm.png
Labels: data-integration

#4279 BGDIINF_SB-3144: set Acess-Control-Allow-Headers to *
  chsdi/response_callbacks.py
Labels: bug

#4275 deploy 20231101: preparation releasenotes
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature

#4280 New Release 2023-11-01-rc1
  chsdi/models/vector/bafu.py
  chsdi/models/vector/evd.py
  chsdi/models/vector/stopo.py
  chsdi/models/vector/uvek.py
  chsdi/models/vector/uvek_solarkataster.py
  chsdi/response_callbacks.py
  chsdi/static/doc/source/releasenotes/index.rst
  chsdi/static/doc/source/services/sdiservices.rst
  chsdi/static/images/legends/ch.agroscope.feuchtflaechenpotential-kulturlandschaft_de.png
  chsdi/static/images/legends/ch.agroscope.feuchtflaechenpotential-kulturlandschaft_en.png
  chsdi/static/images/legends/ch.agroscope.feuchtflaechenpotential-kulturlandschaft_fr.png
  chsdi/static/images/legends/ch.agroscope.feuchtflaechenpotential-kulturlandschaft_it.png
  chsdi/static/images/legends/ch.agroscope.feuchtflaechenpotential-kulturlandschaft_rm.png
  chsdi/static/images/legends/ch.bafu.fauna-wildtierpassagen_de.png
  chsdi/static/images/legends/ch.bafu.fauna-wildtierpassagen_en.png
  chsdi/static/images/legends/ch.bafu.fauna-wildtierpassagen_fr.png
  chsdi/static/images/legends/ch.bafu.fauna-wildtierpassagen_it.png
  chsdi/static/images/legends/ch.bafu.fauna-wildtierpassagen_rm.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_rm.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_de.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_en.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_fr.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_it.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_rm.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_de.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_en.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_fr.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_it.png
  chsdi/static/images/legends/ch.bfe.sachplan-uebertragungsleitungen_anhoerung_rm.png
  chsdi/static/images/legends/ch.meteoschweiz.messwerte-schneehoehe-automatisch-10min_de.png
  chsdi/static/images/legends/ch.meteoschweiz.messwerte-schneehoehe-automatisch-10min_en.png
  chsdi/static/images/legends/ch.meteoschweiz.messwerte-schneehoehe-automatisch-10min_fr.png
  chsdi/static/images/legends/ch.meteoschweiz.messwerte-schneehoehe-automatisch-10min_it.png
  chsdi/static/images/legends/ch.meteoschweiz.messwerte-schneehoehe-automatisch-10min_rm.png
  chsdi/static/images/legends/ch.sbfi.sachplan-cern_anhoerung_de.png
  chsdi/static/images/legends/ch.sbfi.sachplan-cern_anhoerung_en.png
  chsdi/static/images/legends/ch.sbfi.sachplan-cern_anhoerung_fr.png
  chsdi/static/images/legends/ch.sbfi.sachplan-cern_anhoerung_it.png
  chsdi/static/images/legends/ch.sbfi.sachplan-cern_anhoerung_rm.png
  chsdi/static/images/legends/ch.swisstopo.geologie-reflexionsseismik_de.png
  chsdi/static/images/legends/ch.swisstopo.geologie-reflexionsseismik_en.png
  chsdi/static/images/legends/ch.swisstopo.geologie-reflexionsseismik_fr.png
  chsdi/static/images/legends/ch.swisstopo.geologie-reflexionsseismik_it.png
  chsdi/static/images/legends/ch.swisstopo.geologie-reflexionsseismik_rm.png
  chsdi/static/vectorStyles/ch.bafu.hydroweb-warnkarte_national.json
  chsdi/static/vectorStyles/ch.meteoschweiz.messwerte-schneehoehe-automatisch-10min.json
  chsdi/templates/htmlpopup/bafu_fauna_wildtierpassagen.mako
  chsdi/templates/htmlpopup/fida_hfp1.mako
  chsdi/templates/htmlpopup/fida_lfp1.mako
  chsdi/templates/htmlpopup/geologie_reflexionsseismik_line.mako
  chsdi/templates/htmlpopup/geologie_reflexionsseismik_poly.mako
  chsdi/templates/htmlpopup/sbfi_sachplan_cern_anhoerung_line.mako
  chsdi/templates/htmlpopup/sbfi_sachplan_cern_anhoerung_pnt.mako
  chsdi/templates/htmlpopup/sbfi_sachplan_cern_anhoerung_poly.mako
Labels: new-release
