Repository geoadmin/mf-chsdi3, pull requests merged in 2023-03, with the labels that each got.

#4145 BGDIDIC-1783: rework lfp2/hfp2
  chsdi/models/vector/kogis.py
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/fixpunkte.mako
Labels: feature

#4146 BGDIDIC-1783: translate status and punktzeichen attribute value
  chsdi/templates/htmlpopup/fixpunkte.mako
Labels: feature

#4147 BGDIDIC-1709: hydroweb turnaround with vectorStyles due to schedule
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_gefahren.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwasserzustand.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_temperatur.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_zustand.json
Labels: feature

#4148 BGDIINF-1709: bydroweb turnaround reset legend images
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_rm.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_rm.png
Labels: feature

#4149 BGDIDIC-689 + BGDIDIC-690: update legend image
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-arbeitsstaetten_de.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-arbeitsstaetten_en.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-arbeitsstaetten_fr.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-arbeitsstaetten_it.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-arbeitsstaetten_rm.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-beschaeftigte_vollzeitaequivalente_de.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-beschaeftigte_vollzeitaequivalente_en.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-beschaeftigte_vollzeitaequivalente_fr.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-beschaeftigte_vollzeitaequivalente_it.png
  chsdi/static/images/legends/ch.bfs.betriebszaehlungen-beschaeftigte_vollzeitaequivalente_rm.png
Labels: data-integration

#4150 BGDIDIC-2544: update en it legends
  chsdi/static/images/legends/ch.bafu.klima-co2_ausstoss_gebaeude_de.png
  chsdi/static/images/legends/ch.bafu.klima-co2_ausstoss_gebaeude_en.png
  chsdi/static/images/legends/ch.bafu.klima-co2_ausstoss_gebaeude_fr.png
  chsdi/static/images/legends/ch.bafu.klima-co2_ausstoss_gebaeude_it.png
  chsdi/static/images/legends/ch.bafu.klima-co2_ausstoss_gebaeude_rm.png
Labels: feature

#4152 BGDIDIC-1789: Fixing tooltip when no alti is provided
  chsdi/templates/htmlpopup/fixpunkte.mako
Labels: bug

#4144 deploy-20230315: added releasenotes 20230315
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature

#4155 Deploy 2023-03-15: Fix korrupt hydroweb json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwasser.json
Labels: bug

#4156 deploy 20230315: the layer ch.astra.strassenverkehrszaehlung-uebergeo…
  chsdi/models/vector/uvek.py
Labels: bug

#4158 deploy 20230315: added missing tooltip for verkehrszaehlung
  chsdi/templates/htmlpopup/verkehrszaehlung_uebergeordnet.mako
Labels: bug

#4159 BGDIDIC-1490: update bafu url
  chsdi/templates/htmlpopup/wasserentnahme.mako
Labels: feature

#4161 Shorten releasenotes, as the file became quite long
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature

#4163 BGDIINF_SB-2838: Avoid crash in mako due to 104 Connection Broken Exception
  Pipfile.lock
  chsdi/templates/htmlpopup/windatlas50.mako
Labels: bug

#4164 BGDIDIC-1033: Fixing a python3 migration bug in kernkrakfwerk.mako
  chsdi/templates/htmlpopup/kernkraftwerke.mako
Labels: bug

#4165 BGDIDIC-1905: remove raster tooltip
  chsdi/models/grid/__init__.py
  chsdi/templates/htmlpopup/phosphor.mako
  chsdi/templates/htmlpopup/stickstoff.mako
Labels: feature

#4167 Feat bgdidic 997 geologie bohrungen tiefer 500
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/bohrungen_tiefer_500.mako
Labels: feature

#4168 BGDIDIC-1896: remove decommissioned model
  chsdi/models/vector/oereb/vbs.py
Labels: feature
