Repository geoadmin/mf-chsdi3, pull requests merged in 2023-06, with the labels that each got.

#4198 BGDIDIC-2600 BGDIDIC-2601 use id from the data itself
  chsdi/models/vector/uvek.py
Labels: bug, data-integration

#4200 BGDIDIC-2468: new vectorstyle for hydroweb-messstationen
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwasser.json
Labels: feature

#4201 BGDIDIC-2468: new styles for hydroweb
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_gefahren.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwasserzustand.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_temperatur.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_zustand.json
Labels: feature

#4202 BGDIINF_SB-2804: rm diemo model
  chsdi/config/base.ini.in
  chsdi/models/__init__.py
  chsdi/models/vector/diemo.py
Labels: bug

#4207 BGDIDIC-2599 configure model for new layer
  chsdi/models/vector/uvek.py
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_de.png
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_en.png
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_fr.png
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_it.png
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_rm.png
  chsdi/templates/htmlpopup/bazl_intrinsisches_bodenrisiko.mako
Labels: data-integration

#4211 BGDIDIC-2599 Add null constraint in template
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/bazl_intrinsisches_bodenrisiko.mako
Labels: data-integration

#4213 BGDIDIC-1709: new legends 4 hydroweb-messstationen_temperatur
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_rm.png
Labels: feature

#4217 BGDIDIC-1709: reset hydroweb styles
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_gefahren.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwasserzustand.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_temperatur.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_zustand.json
Labels: feature

#4181 BGDIDIC-2331: link_original will be provided as full link by data-owner
  chsdi/templates/htmlpopup/geologischer_atlas_profil.mako
Labels: feature

#4218 BGDIDIC-1293: fix bwatercat translations
  chsdi/templates/htmlpopup/gewaesserschutz_badewasserqualitaet.mako
Labels: feature

#4219 BGDIINF_SB-2950: by default pyramid did not catch all exception and log them
  Pipfile
  Pipfile.lock
  chsdi/config/base.ini.in
Labels: feature

#4214 Preparation to fill in releasenotes 20230628
  chsdi/static/doc/source/releasenotes/index.rst
  chsdi/static/doc/source/services/sdiservices.rst
Labels: feature

#4221 reset style for hydroweb-messstationen_grundwasser
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwasser.json
Labels: bug

#4222 Fixing table in releasnotes
  chsdi/static/doc/source/releasenotes/index.rst
Labels: bug
