Repository geoadmin/mf-chsdi3, pull requests merged in 2023-08, with the labels that each got.

#4231 BGDIINF_SB-3049: considering infinity to be an invalid coordinate for…
  chsdi/lib/helpers.py
Labels: bug

#4228 BGDIDIC-643: feedback topo
  chsdi/lib/helpers.py
  chsdi/templates/htmlpopup/lubis_stac.mako
Labels: feature

#4230 BGDIINF_SB-3047: Removed final resolution from definition
  chsdi/static/doc/source/index.rst
Labels: bug

#4233 Feat bgdidic 643 stac master
  chsdi/models/vector/lubis.py
  chsdi/templates/htmlpopup/lubis_stac.mako
Labels: feature

#4232 BGDIDIC-2624 new layer milchmarktregionen
  chsdi/models/vector/evd.py
  chsdi/static/images/legends/ch.blw.milchmarktregionen_de.png
  chsdi/static/images/legends/ch.blw.milchmarktregionen_en.png
  chsdi/static/images/legends/ch.blw.milchmarktregionen_fr.png
  chsdi/static/images/legends/ch.blw.milchmarktregionen_it.png
  chsdi/static/images/legends/ch.blw.milchmarktregionen_rm.png
  chsdi/templates/htmlpopup/milchmarktregionen.mako
Labels: data-integration

#4234 BGDIDIC-665: add 2023 to shared legend
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk25.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_rm.png
Labels: feature

#4237 BGDIDIC-2474: Refactoring elektrische anlagen. taking zoom level into…
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/bfe_elektrische_anlagen_ueber_36_station_point.mako
  chsdi/templates/htmlpopup/bfe_elektrische_anlagen_ueber_36_station_poly.mako
Labels: feature

#4239 BGDIDIC-2627 add layer legend
  chsdi/static/images/legends/ch.blw.hanglagen-abschwemmung_de.png
  chsdi/static/images/legends/ch.blw.hanglagen-abschwemmung_en.png
  chsdi/static/images/legends/ch.blw.hanglagen-abschwemmung_fr.png
  chsdi/static/images/legends/ch.blw.hanglagen-abschwemmung_it.png
  chsdi/static/images/legends/ch.blw.hanglagen-abschwemmung_rm.png
Labels: data-integration

#4240 BGDIDIC-2599 update legend
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_de.png
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_en.png
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_fr.png
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_it.png
  chsdi/static/images/legends/ch.bazl.intrinsisches-bodenrisiko_sora_rm.png
Labels: data-integration

#4244 BGDIDIC-2474: added missing mako for elektrische anlagen
  chsdi/templates/htmlpopup/bfe_elektrische_anlagen_ueber_36_station.mako
Labels: feature

#4243 BGDIDIC-1703: new style for hydroweb
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwasserzustand.json
Labels: feature

#4241 BGDIDIC-2624 improve layer
  chsdi/models/vector/evd.py
Labels: data-integration

#4246 BGDIDIC-1711: update styles hydroweb-messstationen
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_gefahren.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwassertemperatur.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_temperatur.json
Labels: feature

#4247 BGDIDIC-2474: elektrische anlagen smaller legends
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_fr.png
  chsdi/static/images/legends/ch.bfe.elektrische-anlagen_ueber_36_it.png
Labels: feature

#4251 BGDIDIC-1706: update stylesheet and legend 4 hydroweb
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_gefahren_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_gefahren_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_gefahren_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_gefahren_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_gefahren_rm.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwassertemperatur_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwassertemperatur_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwassertemperatur_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwassertemperatur_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwassertemperatur_rm.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_grundwasserzustand_rm.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_temperatur_rm.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_zustand_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_zustand_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_zustand_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_zustand_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-messstationen_zustand_rm.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_de.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_en.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_fr.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_it.png
  chsdi/static/images/legends/ch.bafu.hydroweb-warnkarte_national_rm.png
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_gefahren.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwassertemperatur.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_grundwasserzustand.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_temperatur.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_zustand.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-warnkarte_national.json
Labels: feature

#4252 BGDIDIC-2599 adapt data type to fit table
  chsdi/models/vector/uvek.py
Labels: bug, data-integration

#4253 BGDIDIC-1711: Fix brackets in hydroweb vectorStyles
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_gefahren.json
  chsdi/static/vectorStyles/ch.bafu.hydroweb-messstationen_zustand.json
Labels: bug
