Repository geoadmin/mf-chsdi3, pull requests merged in 2024-12, with the labels that each got.

#4498 PB-1241: remove akhet library and upgrade lark_parser
  Pipfile
  Pipfile.lock
  apache/wsgi-py3.conf.in
  chsdi/__init__.py
  chsdi/lib/parser.py
  docker-entrypoint.sh
Labels: feature

#4501 BGDIDIC-403: add new attributes gpstime_min and gpstime_max
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/swisssurface3d.mako
Labels: data-integration

#4502 BGDIDIC-1370 Remove Rasterization in Tooltip
  chsdi/models/vector/uvek.py
Labels: data-integration

#4504 PB-1269, PB-1241: Fix cross domain policy
  apache/wsgi-py3.conf.in
  chsdi/response_callbacks.py
  chsdi/subscribers.py
Labels: bug

#4487 PB-974: Migration from trias to ojp for transport stop requests
  .env.ci
  .env.default
  Pipfile
  Pipfile.lock
  chsdi/config/base.ini.in
  chsdi/lib/opentransapi/opentransapi.py
  chsdi/views/stationboard.py
  tests/integration/helpers.py
  tests/integration/test_opentransapi.py
  tests/integration/test_stationboard.py
Labels: feature

#4507 BGDIDIC-651 Remove Rasterization in Tool-Tip
  chsdi/models/vector/dritte.py
Labels: data-integration

#4509 BGDIDIC-1370 Remove rasterization also for anhoerung layer
  chsdi/models/vector/uvek.py
Labels: data-integration

#4511 PB-974: secrets.yml and README.md
  README.md
  secrets.yml
Labels: feature

#4513 deploy-20241218: Release notes
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature
