Repository geoadmin/mf-chsdi3, pull requests merged in 2024-09, with the labels that each got.

#4435 PB-885: use new datasource for swissimage hist
  chsdi/models/vector/stopo.py
Labels: data-integration

#4437 PB-201: Updated the CI name for milestone branch protection
  .github/workflows/create-milestone.yml
Labels: feature

#4438 BGDIDIC-642: with the migration to stac the image_number is empty
  chsdi/templates/htmlpopup/lubis_terra.mako
Labels: bug

#4439 BGDIDIC-662: add new release 2024
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_rm.png
Labels: data-integration

#4440 BGDIDIC-1259: download links are suffixed on stac with _2056
  chsdi/templates/htmlpopup/lubis_schraegaufnahmen.mako
Labels: data-integration

#4446 Revert "BGDIDIC-2865: fine tuning tooltip geometry sizes"
  chsdi/models/vector/vbs.py
Labels: data-integration
