Repository geoadmin/mf-chsdi3, pull requests merged in 2024-01, with the labels that each got.

#4308 BGDIDIC-2709 Adapt web url in tooltip
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/sug_facilities.mako
  chsdi/templates/htmlpopup/sug_planning.mako
Labels: data-integration

#4310 BGDIDIC-2709 Adapt tooltip
  chsdi/models/vector/uvek.py
  chsdi/templates/htmlpopup/sug_facilities.mako
  chsdi/templates/htmlpopup/sug_planning.mako
Labels: data-integration

#4311 BGDIDIC-646: activate stac support for lubis farbe images
  chsdi/models/vector/lubis.py
Labels: feature

#4309 Feat relnotes 20240131
  chsdi/static/doc/source/releasenotes/index.rst
  chsdi/static/doc/source/services/sdiservices.rst
Labels: feature

#4312 New Release 2024-01-31-rc1
  chsdi/models/vector/lubis.py
  chsdi/models/vector/uvek.py
  chsdi/static/doc/source/releasenotes/index.rst
  chsdi/static/doc/source/services/sdiservices.rst
  chsdi/templates/htmlpopup/sug_facilities.mako
  chsdi/templates/htmlpopup/sug_planning.mako
Labels: new-release

#4314 Typos on releasenotes title
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature
