Repository geoadmin/mf-chsdi3, pull requests merged in 2024-07, with the labels that each got.

#4407 deploy: 2024-07-03: initialising releasenotes
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature

#4410 add a documentation about the optional coord parameter on the htmlpopup
  chsdi/static/doc/source/services/sdiservices.rst
Labels: feature

#4411 PB-764 made polyfill url configurable via env
  .env.ci
  .env.default
  chsdi/config/base.ini.in
  chsdi/templates/loader.js
  chsdi/views/loader.py
Labels: bug

#4415 BGDIDIC-2849: fix typo in model
  chsdi/models/vector/edi.py
Labels: data-integration

#4421 mf-geoadmin3.dev.bgdi.ch has been replaced with sys-map.dev.bgdi.ch
  .env.ci
  .env.default
Labels: feature
