Repository geoadmin/mf-chsdi3, pull requests merged in 2024-06, with the labels that each got.

#4382 BGDIDIC-2832: ch.swisstopo.geologie-hartsteinvorkommen
  chsdi/models/vector/stopo.py
  chsdi/static/images/legends/ch.swisstopo.geologie-hartsteinvorkommen_de.png
  chsdi/static/images/legends/ch.swisstopo.geologie-hartsteinvorkommen_en.png
  chsdi/static/images/legends/ch.swisstopo.geologie-hartsteinvorkommen_fr.png
  chsdi/static/images/legends/ch.swisstopo.geologie-hartsteinvorkommen_it.png
  chsdi/static/images/legends/ch.swisstopo.geologie-hartsteinvorkommen_rm.png
  chsdi/templates/htmlpopup/hartsteinvorkommen.mako
Labels: data-integration

#4386 BGDIDIC-2829: use stable and global id
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/hartsteinabbau_mining.mako
  chsdi/templates/htmlpopup/hartsteinabbau_production.mako
Labels: data-integration

#4388 BGDIDIC-2139 update legend
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_de.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_en.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_fr.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_it.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_rm.png
Labels: data-integration

#4391 BGDIDIC-2271: arealstatistik 1979-2020
  chsdi/models/vector/edi.py
  chsdi/templates/htmlpopup/arealstatistik_std.mako
Labels: data-integration

#4393 BGDIDIC-2272: update timeseries arealstatistik-bodenbedeckung
  chsdi/models/vector/edi.py
  chsdi/templates/htmlpopup/arealstatistik_nolc.mako
Labels: data-integration

#4394 mapExtent and imageDisplay are supported and needed for the htmlpopup
  chsdi/static/doc/source/services/sdiservices.rst
Labels: feature

#4396 BGDIDIC-2271: update legends
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_de.png
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_en.png
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_fr.png
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_it.png
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_rm.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_de.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_en.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_fr.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_it.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_rm.png
Labels: data-integration

#4397 BGDIDIC-2771: update legends
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_de.png
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_en.png
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_fr.png
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_it.png
  chsdi/static/images/legends/ch.bfs.arealstatistik-bodenbedeckung_rm.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_de.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_en.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_fr.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_it.png
  chsdi/static/images/legends/ch.bfs.arealstatistik_rm.png
Labels: data-integration

#4399 update legends with new translataions
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_de.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_en.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_fr.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_it.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_rm.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_de.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_en.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_fr.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_it.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-restaurants_rm.png
Labels: data-integration

#4400 PB-711 : broken link to STAC API documentation
  chsdi/static/doc/source/index.rst
Labels: bug

#4402 BGDIDIC-2139 update legend
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_de.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_en.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_fr.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_it.png
  chsdi/static/images/legends/ch.bfs.erreichbarkeit-apotheken_rm.png
Labels: data-integration
