Repository geoadmin/mf-chsdi3, pull requests merged in 2024-10, with the labels that each got.

#4447 Relesenotes 2024-10-09
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature

#4448 New Release 2024-10-09-rc1
  .github/workflows/create-milestone.yml
  chsdi/models/vector/uvek.py
  chsdi/models/vector/vbs.py
  chsdi/static/doc/source/releasenotes/index.rst
  chsdi/static/images/legends/ch.babs.notfalltreffpunkte_de.png
  chsdi/static/images/legends/ch.babs.notfalltreffpunkte_en.png
  chsdi/static/images/legends/ch.babs.notfalltreffpunkte_fr.png
  chsdi/static/images/legends/ch.babs.notfalltreffpunkte_it.png
  chsdi/static/images/legends/ch.babs.notfalltreffpunkte_rm.png
  chsdi/static/images/legends/ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner_de.png
  chsdi/static/images/legends/ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner_en.png
  chsdi/static/images/legends/ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner_fr.png
  chsdi/static/images/legends/ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner_it.png
  chsdi/static/images/legends/ch.bfs.volkszaehlung-bevoelkerungsstatistik_einwohner_rm.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage-dop10.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.images-swissimage.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk100.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk200.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.pixelkarte-pk50.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d-raster.metadata_rm.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_de.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_en.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_fr.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_it.png
  chsdi/static/images/legends/ch.swisstopo.swisssurface3d.metadata_rm.png
  chsdi/templates/htmlpopup/bfe_ladebedarfswelt_ladepunkte.mako
  chsdi/templates/htmlpopup/lubis_schraegaufnahmen.mako
  chsdi/templates/htmlpopup/lubis_terra.mako
  chsdi/templates/htmlpopup/notfalltreffpunkte.mako
Labels: new-release

#4461 BGDIDIC-1408: Schneerouten as Vectors
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/karto_schneerouten.mako
Labels: data-integration

#4464 BGDIDIC-1408: small adjustment tooltip skitouren
  chsdi/templates/htmlpopup/karto_schneerouten.mako
Labels: data-integration

#4465 BGDIDIC-1408: improved tooltip skitouren
  chsdi/templates/htmlpopup/karto_schneerouten.mako
Labels: data-integration
