Repository geoadmin/mf-chsdi3, pull requests merged in 2024-11, with the labels that each got.

#4466 BGDIDIC-643: aerialimages bucket migration clean-up
  .env.ci
  .env.default
  chsdi/__init__.py
  chsdi/config/base.ini.in
  chsdi/models/vector/lubis.py
  chsdi/templates/htmlpopup/lubis.mako
  chsdi/templates/htmlpopup/lubis_schraegaufnahmen.mako
  chsdi/templates/htmlpopup/lubis_stac.mako
  chsdi/templates/htmlpopup/lubis_terra.mako
  chsdi/templates/index.mako
  chsdi/templates/luftbilder/lubis_map.mako
  chsdi/templates/luftbilder/viewer.mako
  chsdi/views/luftbilder.py
  tests/integration/test_features_service.py
  tests/integration/test_luftbilder.py
Labels: data-integration

#4470 BGDIDIC-2875: Add legends bahnen winter
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_de.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_en.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_fr.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_it.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_rm.png
Labels: data-integration

#4472 BGDIDIC-1804: feedback karto
  chsdi/models/vector/stopo.py
  chsdi/templates/htmlpopup/karto_schneeschuhrouten.mako
  chsdi/templates/htmlpopup/karto_skitouren.mako
Labels: data-integration

#4476 BGDIDIC-1480: Tailored legends for topic snow
  chsdi/static/images/legends/ch.swisstopo-karto.schneeschuhrouten_de.png
  chsdi/static/images/legends/ch.swisstopo-karto.schneeschuhrouten_en.png
  chsdi/static/images/legends/ch.swisstopo-karto.schneeschuhrouten_fr.png
  chsdi/static/images/legends/ch.swisstopo-karto.schneeschuhrouten_it.png
  chsdi/static/images/legends/ch.swisstopo-karto.schneeschuhrouten_rm.png
  chsdi/static/images/legends/ch.swisstopo-karto.skitouren_de.png
  chsdi/static/images/legends/ch.swisstopo-karto.skitouren_en.png
  chsdi/static/images/legends/ch.swisstopo-karto.skitouren_fr.png
  chsdi/static/images/legends/ch.swisstopo-karto.skitouren_it.png
  chsdi/static/images/legends/ch.swisstopo-karto.skitouren_rm.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_de.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_de_big.pdf
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_en.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_en_big.pdf
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_fr.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_fr_big.pdf
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_it.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_it_big.pdf
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_rm.png
  chsdi/static/images/legends/ch.swisstopo.bahnen-winter_rm_big.pdf
Labels: data-integration

#4478 BGDIDIC-1408: aktivate extendet tooltip
  chsdi/templates/legend.mako
Labels: data-integration

#4481 Releasenotes 2024-11-13
  chsdi/static/doc/source/releasenotes/index.rst
Labels: feature

#4489 BGDIDIC-2882: add model that has been removed by mistake
  chsdi/models/vector/uvek.py
Labels: bug

#4486 PB-1141 : update layer list in FAQ
  chsdi/__init__.py
  chsdi/static/doc/source/api/faq/index.rst
  chsdi/views/layers.py
  tests/integration/test_layers_service.py
Labels: bug
