Repository geoadmin/mf-chsdi3, pull requests merged in 2024-03, with the labels that each got.

#4340 BGDIDIC-984: Revert activate time support / timeseries for pk25
  chsdi/models/vector/stopo.py
Labels: data-integration

#4350 PB-130: As announced, api3 is not accepting HTTP PUT, POST and DELETE…
  chsdi/__init__.py
  chsdi/config/base.ini.in
  chsdi/response_callbacks.py
Labels: feature

#4352 remove unsupported lang
  chsdi/templates/htmlpopup/bakom_standorte_mobilfunkanlagen.mako
Labels: bug

#4353 PB-130: HTTP 405 when method not allowed.
  apache/25-mf-chsdi3.conf.in
  chsdi/__init__.py
Labels: feature

#4354 Revert "Merge pull request #4340 from geoadmin/data_BGDIDIC-984_revert"
  chsdi/models/vector/stopo.py
Labels: data-integration
