Repository geoadmin/mf-chsdi3, pull requests merged in 2025-01, with the labels that each got.

#4517 PB-760: Updated build badge
  README.md
Labels: feature

#4518 PB-1319: corrected timestamp formats and adapted format_time() to fix erroneous 1h offset for departure times
  chsdi/lib/opentransapi/opentransapi.py
  tests/integration/test_opentransapi.py
Labels: bug

#4520 BGDIDIC-2078 remove rasterization
  chsdi/models/vector/uvek.py
Labels: data-integration

#4521 BGDIDIC-1317 SIL remove rasterization
  chsdi/models/vector/uvek.py
Labels: data-integration

#4526 BGDIDIC-1841: update link source
  chsdi/templates/htmlpopup/cadastralwebmap.include.mako
Labels: feature
